#   ██╗    ██╗██╗   ██╗██████╗ ██████╗ 
#   ██║    ██║╚██╗ ██╔╝██╔══██╗██╔══██╗
#   ██║ █╗ ██║ ╚████╔╝ ██████╔╝██████╔╝
#   ██║███╗██║  ╚██╔╝  ██╔═══╝ ██╔══██╗
#   ╚███╔███╔╝   ██║   ██║     ██║  ██║
#    ╚══╝╚══╝    ╚═╝   ╚═╝     ╚═╝  ╚═╝

auth {
    fingerprint:enabled = true
}

background {
    monitor =
    path = ~/Pictures/Wallpaper/blade.jpg
    blur_passes = 1
    blur_size = 7
    noise = 0.0117
    contrast = 0.89
    brightness = 0.82
    vibrancy = 0.17
    vibrancy_darkness = 0.0
}

input-field {
    monitor = 
    size = 400, 50
    outline_thickness = 2

    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1

    # --- Colores estéticos ---
    outer_color = rgba(c3c6fbcc)        # borde principal
    inner_color = rgba(1e2030ee)        # fondo input
    font_color  = rgba(c3c6fbdd)        # texto

    check_color = rgba(9eceaaff)        # success (verde frío)
    fail_color  = rgba(f7768eff)        # error suave

    fade_on_empty = true
    fade_timeout = 1000

    placeholder_text = <i> </i>
    hide_input = false

    font_family = JetBrainsMono NerdFont
    rounding = -1

    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300

    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, -20
    halign = center
    valign = center
}

# -------- Clock --------
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(c3c6fbff)
    font_size = 80
    font_family = JetBrainsMono NerdFont Extrabold
    position = 0, 150
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

# -------- User --------
label {
    monitor =
    text = $USER...
    color = rgba(c3c6fbcc)
    font_size = 20
    font_family = JetBrainsMono NerdFont
    position = 0, 50
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

